name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch.
  pull_request:
    branches:
      - main  # Triggers the workflow on pull requests to the main branch.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Uses Azure Service Principal for login.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Sets up Docker Buildx

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: weatherappregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Specifies the build context path.
        file: ./dockerfile  # Specifies the location of the Dockerfile.
        push: true  # Pushes the image to the registry after build.
        tags: weatherappregistry.azurecr.io/weather-app-image:latest  # Tags the image.

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: weather-app  # The name of your Azure Web App.
        images: weatherappregistry.azurecr.io/weather-app-image:latest  # The image to deploy.

    - name: Azure Logout
      if: always()  # Ensures this step will always run, regardless of earlier steps' success or failure.
      run: az logout
